#!/bin/sh
# $HOME/embr-iw-speedland-demo/python/sl-start-daemon.py
# $HOME/embr-iw-speedland-demo/python/sl-finish1-daemon.py
# $HOME/embr-iw-speedland-demo/python/sl-finish2-daemon.py
# $HOME/embr-iw-speedland-demo/python/sl-signup-daemon.py

### BEGIN INIT INFO
# Provides:          sl-daemon
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start a program at boot
# Description:       A simple script from www.stuffaboutcode.com which will start / stop a program a boot / shutdown.
### END INIT INFO

# If you want a command to always run, put it here
DAEMON_PATH="/home/pi/embr-iw-speedlane-demo/python"

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting embr daemons"
    # run application you want to start
    $DAEMON_PATH/sl-start-daemon.py start
    $DAEMON_PATH/sl-finish1-daemon.py start
    $DAEMON_PATH/sl-finish2-daemon.py start
    $DAEMON_PATH/sl-signup-daemon.py start
    ;;
  stop)
    echo "Stopping embr daemons"
    # kill application you want to stop
    $DAEMON_PATH/sl-start-daemon.py stop
    $DAEMON_PATH/sl-finish1-daemon.py stop
    $DAEMON_PATH/sl-finish2-daemon.py stop
    $DAEMON_PATH/sl-signup-daemon.py stop
    ;;
  *)
    echo "Usage: /etc/init.d/sl-daemon {start|stop}"
    exit 1
    ;;
esac

exit 0
